<template>
  <div class="formInfo">
    <van-cell title="共享面试表">
      <template #right-icon>
        <span class="doBtn" @click="goRouter">操作记录</span>
      </template>
    </van-cell>
    <van-form label-width="150px">
      <van-cell-group>
        <van-field
          label="司机姓名"
          :value="obj.name"
          readonly
          colon
        />
        <van-field
          label="司机电话"
          :value="obj.phone"
          readonly
          colon
        />
        <van-field
          label="面试地址"
          colon
          value="暂无"
          readonly
        />
        <!-- :value="`${obj.InterviewInfoVO.interviewProvinceName}${obj.InterviewInfoVO.interviewCityName}${obj.InterviewInfoVO.interviewCountyName}`" -->
        <van-field
          label="工作城市"
          :value="obj.workCityName"
          readonly
          colon
        />
        <van-field
          label="司机年龄"
          value="age"
          readonly
          colon
        />
        <van-field
          label="是否有车"
          colon
          value="hasOwnCar"
          readonly
        />
        <van-field
          label="当前车型"
          value="currentCarType"
          readonly
          colon
        />
        <van-field
          label="意向驾驶车型"
          value="intentDrivingCarType"
          readonly
          colon
        />
        <van-field
          label="现居住地址"
          colon
          value="暂无"
          readonly
        />
        <van-field
          label="货物运输经验（月）"
          value="experience"
          readonly
          colon
        />
        <van-field
          label="当前是否无业"
          value="currentHasWork"
          readonly
          colon
        />
        <van-field
          label="意向货物类型"
          colon
          value="intentCargoType"
          readonly
        />
        <van-field
          label="意向工作时间段"
          colon
          value="intentWorkDuration"
          readonly
        />
        <van-field
          label="是否能承担较重搬运"
          colon
          value="heavyLifting"
          readonly
        />
        <van-field
          label="邀约渠道"
          colon
          value="sourceChannel"
          readonly
        />
        <van-field
          label="驾照类型"
          colon
          value="drivingLicenceType"
          readonly
        />
        <van-field
          label="是否本地工作车牌"
          colon
          value="isLocalPlate"
          readonly
        />
        <van-field
          label="高意向工作区域"
          colon
          value="intentWork"
          readonly
        />
        <van-field
          label-width="200px"
          label="原收入(去油)(元/月)"
          colon
          value="originIncomeAvg"
          readonly
        />
        <van-field
          label-width="200px"
          label="期望收入(去油)(元/月)"
          colon
          value="expIncomeAvg"
          readonly
        />
        <van-field
          label="从业时间（月）"
          colon
          value="workDuration"
          readonly
        />
        <van-field
          label="零散活占比（%）"
          colon
          value="scatteredJobRate"
          readonly
        />
        <van-field
          label="是否新能源"
          colon
          value="isNewEnergy"
          readonly
        />
      </van-cell-group>
      <br>
      <van-cell title="专车面试表">
        <template #right-icon>
          <span class="doBtn" @click="goRouter">操作记录</span>
        </template>
      </van-cell>
      <van-cell-group>
        <van-field
          label="司机姓名"
          value="name"
          colon
          readonly
        />
        <van-field
          label="司机电话"
          value="phone"
          readonly
          colon
        />
        <van-field
          label="邀约方式"
          value="inviteType"
          colon
          readonly
        />
        <van-field
          label="工作城市"
          value="workCity"
          readonly
          colon
        />
        <van-field
          label="邀约渠道"
          value="sourceChannel"
          colon
          readonly
        />
        <van-field
          label="您是从哪里了解到我们的加盟方式"
          value="whereKnow"
          colon
          readonly
        />
        <van-field
          label="重代理姓名"
          value="heavyAgentName"
          readonly
          colon
        />
        <van-field
          label="司机年龄"
          value="age"
          colon
          readonly
        />
        <van-field
          label="现居住地址"
          value="liveaddress"
          readonly
          colon
        />
        <van-field
          label="意向工作区域"
          value="intentWork"
          colon
          readonly
        />
        <van-field
          label="意向配送模式"
          value="intentDeliveryMode"
          readonly
          colon
        />
        <van-field
          label="意向货物类型"
          value="intentCargoType"
          colon
          readonly
        />
        <van-field
          label="意向工作时间段"
          value="intentWorkDuration"
          readonly
          colon
        />
        <van-field
          label="原收入(去油)(元/月)"
          value="originIncomeAvg"
          colon
          readonly
        />
        <van-field
          label="期望收入(去油)(元/月)"
          value="expIncomeAvg"
          readonly
          colon
        />
        <van-field
          label="户籍类型"
          value="householdType"
          colon
          readonly
        />
        <van-field
          label="户籍地址"
          value="householdAddress"
          readonly
          colon
        />
        <van-field
          label="户籍详细地址"
          value="输入框只读"
          colon
          readonly
        />
        <van-field
          label="子女数"
          value="childNum"
          readonly
          colon
        />
        <van-field
          label="货物运输经验（月）"
          value="experience"
          colon
          readonly
        />
        <van-field
          label="当前是否无业"
          value="currentHasWork"
          readonly
          colon
        />
        <van-field
          label="实际货车驾龄（月）"
          value="drivingAge"
          colon
          readonly
        />
        <van-field
          label="本城市居住时长（月）"
          value="livingAge"
          readonly
          colon
        />
        <van-field
          label="驾照类型"
          value="drivingLicenceType"
          colon
          readonly
        />
        <van-field
          label="是否有车"
          value="hasOwnCar"
          readonly
          colon
        />
        <van-field
          label="当前车型"
          value="currentCarType"
          colon
          readonly
        />
        <van-field
          label="意向驾驶车型"
          value="intentDrivingCarType"
          readonly
          colon
        />
        <van-field
          label="最大可支付首付款"
          value="maxAdvancePayment"
          colon
          readonly
        />
        <van-field
          label="是否能承担较重搬运"
          value="heavyLifting"
          readonly
          colon
        />
        <van-field
          label="是否提供个人征信"
          value="providePersonalCredit"
          colon
          readonly
        />
        <van-field
          label="投资决策权"
          value="strategyRight"
          readonly
          colon
        />
        <van-field
          label="如果有机会和云鸟合作，你看中的是什么？"
          value="cooperateFocusPoint"
          colon
          readonly
        />
        <van-field
          label="最终决定你和云鸟合作的关键因素是什么？"
          value="cooperateKeyFactor"
          readonly
          colon
        />
        <van-field
          label="是否是高意向司机"
          value="isAdvancedIntention"
          colon
          readonly
        />
        <van-field
          label="备注"
          value="remarks"
          readonly
          colon
        />
      </van-cell-group>
    </van-form>
  </div>
</template>

<script>
export default {
  props: {
    obj: {
      type: Object,
      default: () => {}
    }
  },
  data() {
    return {};
  },
  methods: {
    goRouter() {
      this.$router.push({ path: '/driverLog', query: { id: '123' }})
    }
  }
};
</script>
<style lang="less" scoped>
.formInfo {
  .van-cell-group {
    padding: 15px 0;
    box-sizing: border-box;
  }
  .van-cell {
    padding: 3px 15px;
    box-sizing: border-box;
  }
  .van-cell__title {
    font-size: 15px;
    color: #3c4353;
  }
  .doBtn {
    font-size: 12px;
    color: #7f8fbd;
  }
}
</style>
